import {
  InvoiceAdvancePayments,
  InvoiceInput,
  InvoiceItemDtos,
  InvoiceUpdate,
  PurchaseTaxAndCharges,
} from "../types/procurement/invoice/invoice-types"

export const DEFAULT_PURCHASE_INVOICE_VALUES: InvoiceInput | InvoiceUpdate = {
  requisitionId: 0,
  purchaseOrderId: 0,
  supplierId: 0,
  paymentTermsId: 0,
  warehouseId: 0,
  invoiceDate: "",
  dueDate: "",
  requestedBy: "",
  projectName: "",
  billingStatus: "",
  fiscalPosition: "",
  expectedDeliveryDate: "",
  priority: "",
  isReturned: false,
  isStockUpdated: false,
  companyId: 0,
  companyName: "",
  currencyId: 0,
  currencyName: "",
  taxCategoryId: 0,
  taxCategoryName: "",
  purchaseTaxTemplateId: 0,
  purchaseTaxTemplateName: "",
  supplierAddress: "",
  supplierStreet: "",
  supplierCity: "",
  supplierState: "",
  supplierCountry: "",
  supplierZipCode: "",
  supplierContactName: "",
  supplierContactEmail: "",
  supplierContactPhone: "",
  shippingAddress: "",
  shippingStreet: "",
  shippingCity: "",
  shippingState: "",
  shippingCountry: "",
  shippingZipCode: "",
  shippingContactPerson: "",
  shippingContactPhone: "",
  shippingContactEmail: "",
  companyAddress: "",
  companyStreet: "",
  companyCity: "",
  companyState: "",
  companyCountry: "",
  companyZipCode: "",
  companyTrn: "",
  companyContactPerson: "",
  companyContactPhone: "",
  companyContactEmail: "",
  creditToId: 0,
  creditToName: "",
  isOpeningEntry: false,
  totalQuantity: 0,
  billAmount: 0,
  totalTax: 0,
  grandTotal: 0,
  netTotalAmount: 0,
  totalAdvance: 0,
  outstandingAmount: 0,
  addDiscountApplyOn: "",
  addDiscountPercent: 0,
  addDiscountAmount: 0,
  writeOffAccountId: 0,
  writeOffCostCenterId: 0,
  writeOffAmount: 0,
  saveInvoiceItemDtos: [],
  invoiceVatTaxDetails: [],
  invoiceAdvancePayments: [],
}

export const DEFAULT_PURCHASE_INVOICE_PRODUCT_ITEMS_VALUES: InvoiceItemDtos = {
  productId: 0,
  itemUnitId: 0,
  itemUnitName: "",
  quantity: 0,
  unitPrice: 0,
  totalPrice: 0,
}

export const DEFAULT_PURCHASE_INVOICE_TAX_AND_CHARGES: PurchaseTaxAndCharges = {
  taxTypeId: 0,
  taxTypeName: "",
  chartOfAccountId: 0,
  chartOfAccountName: "",
  rate: 0,
  amount: 0,
  total: 0,
}

export const DEFAULT_PURCHASE_INVOICE_ADVANCE_PAYMENTS: InvoiceAdvancePayments =
  {
    referenceName: "",
    remarks: "",
    advanceAmount: 0,
    allocatedAmount: 0,
  }
