import { z } from "zod"

import { messages } from "@/config/messages"

export const CreatePurchaseOrderSchema = z.object({
  requisitionId: z
    .number()
    .positive()
    .min(1, { message: messages.requisitionId }),
  supplierId: z.number().positive().min(1, { message: messages.supplierId }),
  paymentTermsId: z
    .number()
    .positive()
    .min(1, { message: messages.paymentTermId }),
  warehouseId: z.number().positive().min(1, { message: messages.warehouseId }),
  poDate: z.string().min(1, { message: messages.poDate }),
  requestedBy: z.string().min(1, { message: messages.requestedBy }),
  projectName: z.string().min(1, { message: messages.projectName }),
  billingStatus: z.string().min(1, { message: messages.billingStatus }),
  fiscalPosition: z.string().min(1, { message: messages.fiscalPosition }),
  expectedDeliveryDate: z
    .string()
    .min(1, { message: messages.expectedDeliveryDate }),
  priority: z.string().min(1, { message: messages.priority }),
  companyId: z.number().positive().min(1, { message: messages.companyId }),
  companyName: z.string().min(1, { message: messages.companyName }),
  currencyId: z.number().positive().min(1, { message: messages.currencyId }),
  currencyName: z.string().optional(),
  taxCategoryId: z.number().optional(),
  taxCategoryName: z.string().optional(),
  purchaseTaxTemplateId: z.number().optional(),
  purchaseTaxTemplateName: z.string().optional(),
  supplierAddress: z.string().optional(),
  supplierStreet: z.string().optional(),
  supplierCity: z.string().optional(),
  supplierState: z.string().optional(),
  supplierCountry: z.string().optional(),
  supplierZipCode: z.string().optional(),
  supplierContactPhone: z.string().optional(),
  supplierContactName: z.string().optional(),
  supplierContactEmail: z.string().optional(),
  shippingAddress: z.string().optional(),
  shippingStreet: z.string().optional(),
  shippingCity: z.string().optional(),
  shippingState: z.string().optional(),
  shippingCountry: z.string().optional(),
  shippingZipCode: z.string().optional(),
  shippingContactName: z.string().optional(),
  shippingContactPhone: z.string().optional(),
  shippingContactEmail: z.string().optional(),
  companyAddress: z.string().optional(),
  companyStreet: z.string().optional(),
  companyCity: z.string().optional(),
  companyState: z.string().optional(),
  companyCountry: z.string().optional(),
  companyZipCode: z.string().optional(),
  companyTrn: z.string().optional(),
  companyContactPerson: z.string().optional(),
  companyContactPhone: z.string().optional(),
  companyContactEmail: z.string().optional(),
  totalQuantity: z.number().optional(),
  orderAmount: z.number().optional(),
  totalTax: z.number().optional(),
  grandTotal: z.number().optional(),
  netTotalAmount: z.number().optional(),
  advancePaid: z.number().optional(),
  addDiscountApplyOn: z.string().optional(),
  addDiscountPercent: z.number().optional(),
  addDiscountAmount: z.number().optional(),
  attachmentFile: z.string().optional(),
  savePurchaseOrderItemDtos: z.array(z.any()).optional(),
  purchaseOrderVatTaxDetails: z.array(z.any()).optional(),
})

export const UpdatePurchaseOrderSchema = z.object({
  requisitionId: z.number().optional(),
  supplierId: z.number().optional(),
  paymentTermsId: z.number().optional(),
  warehouseId: z.number().optional(),
  poDate: z.string().optional(),
  requestedBy: z.string().optional(),
  projectName: z.string().optional(),
  billingStatus: z.string().optional(),
  fiscalPosition: z.string().optional(),
  expectedDeliveryDate: z.string().optional(),
  priority: z.string().optional(),
  companyId: z.number().optional(),
  companyName: z.string().optional(),
  currencyId: z.number().optional(),
  currencyName: z.string().optional(),
  taxCategoryId: z.number().optional(),
  taxCategoryName: z.string().optional(),
  purchaseTaxTemplateId: z.number().optional(),
  purchaseTaxTemplateName: z.string().optional(),
  supplierAddress: z.string().optional(),
  supplierStreet: z.string().optional(),
  supplierCity: z.string().optional(),
  supplierState: z.string().optional(),
  supplierCountry: z.string().optional(),
  supplierZipCode: z.string().optional(),
  supplierContactPhone: z.string().optional(),
  supplierContactName: z.string().optional(),
  supplierContactEmail: z.string().optional(),
  shippingAddress: z.string().optional(),
  shippingStreet: z.string().optional(),
  shippingCity: z.string().optional(),
  shippingState: z.string().optional(),
  shippingCountry: z.string().optional(),
  shippingZipCode: z.string().optional(),
  shippingContactName: z.string().optional(),
  shippingContactPhone: z.string().optional(),
  shippingContactEmail: z.string().optional(),
  companyAddress: z.string().optional(),
  companyStreet: z.string().optional(),
  companyCity: z.string().optional(),
  companyState: z.string().optional(),
  companyCountry: z.string().optional(),
  companyZipCode: z.string().optional(),
  companyTrn: z.string().optional(),
  companyContactPerson: z.string().optional(),
  companyContactPhone: z.string().optional(),
  companyContactEmail: z.string().optional(),
  totalQuantity: z.number().optional(),
  orderAmount: z.number().optional(),
  totalTax: z.number().optional(),
  grandTotal: z.number().optional(),
  netTotalAmount: z.number().optional(),
  advancePaid: z.number().optional(),
  addDiscountApplyOn: z.string().optional(),
  addDiscountPercent: z.number().optional(),
  addDiscountAmount: z.number().optional(),
  attachmentFile: z.string().optional(),
  updatePurchaseOrderItemDtos: z.array(z.any()).optional(),
  purchaseOrderVatTaxDetails: z.array(z.any()).optional(),
})

export type CreatePurchaseOrderInput = z.infer<typeof CreatePurchaseOrderSchema>

export type UpdatePurchaseOrderInput = z.infer<typeof UpdatePurchaseOrderSchema>
