import { z } from "zod"

import { messages } from "@/config/messages"

export const CreateInvoiceSchema = z.object({
  requisitionId: z.number().min(1, { message: messages.requisitionId }),
  purchaseOrderId: z.number().min(1, { message: messages.purchaseOrderId }),
  supplierId: z.number().min(1, { message: messages.supplierId }),
  paymentTermsId: z.number().min(1, { message: messages.paymentTermId }),
  warehouseId: z.number().min(1, { message: messages.warehouseId }),
  invoiceDate: z.string().min(1, { message: messages.invoiceDate }),
  dueDate: z.string().min(1, { message: messages.dueDate }),
  requestedBy: z.string().min(1, { message: messages.requestedBy }),
  projectName: z.string().min(1, { message: messages.projectName }),
  billingStatus: z.string().min(1, { message: messages.billingStatus }),
  fiscalPosition: z.string().min(1, { message: messages.fiscalPosition }),
  expectedDeliveryDate: z
    .string()
    .min(1, { message: messages.expectedDeliveryDate }),
  priority: z.string().min(1, { message: messages.priority }),
  isReturned: z.boolean().optional(),
  isStockUpdated: z.boolean().optional(),
  companyId: z.number().positive().min(1, { message: messages.companyId }),
  companyName: z.string().min(1, { message: messages.companyName }),
  currencyId: z.number().positive().min(1, { message: messages.currencyId }),
  currencyName: z.string().optional(),
  taxCategoryId: z.number().optional(),
  taxCategoryName: z.string().optional(),
  purchaseTaxTemplateId: z.number().optional(),
  purchaseTaxTemplateName: z.string().optional(),
  supplierAddress: z.string().optional(),
  supplierContact: z.string().optional(),
  supplierAddressDetails: z.string().optional(),
  supplierContactName: z.string().optional(),
  supplierContactEmail: z.string().optional(),
  shippingAddress: z.string().optional(),
  shippingAddressDetails: z.string().optional(),
  companyTRN: z.string().optional(),
  companyBillingAddress: z.string().optional(),
  companyAddressDetails: z.string().optional(),
  creditToId: z.number().optional(),
  creditToName: z.string().optional(),
  isOpeningEntry: z.boolean().optional(),
  totalQuantity: z.number().optional(),
  billAmount: z.number().optional(),
  totalTaxes: z.number().optional(),
  grandTotal: z.number().optional(),
  netTotalAmount: z.number().optional(),
  totalAdvance: z.number().optional(),
  outstandingAmount: z.number().optional(),
  addDiscountApplyOn: z.string().optional(),
  addDiscountPercent: z.number().optional(),
  addDiscountAmount: z.number().optional(),
  writeOffAccountId: z.number().optional(),
  writeOffCostCenterId: z.number().optional(),
  writeOffAmount: z.number().optional(),
  saveInvoiceItemDtos: z.array(z.any()).optional(),
  invoiceVatTaxDetails: z.array(z.any()).optional(),
  invoiceAdvancePayments: z.array(z.any()).optional(),
})

export const UpdateInvoiceSchema = z.object({
  requisitionId: z.number().optional(),
  purchaseOrderId: z.number().optional(),
  supplierId: z.number().optional(),
  paymentTermsId: z.number().optional(),
  warehouseId: z.number().optional(),
  invoiceDate: z.string().optional(),
  dueDate: z.string().optional(),
  requestedBy: z.string().optional(),
  projectName: z.string().optional(),
  billingStatus: z.string().optional(),
  fiscalPosition: z.string().optional(),
  expectedDeliveryDate: z.string().optional(),
  priority: z.string().optional(),
  isReturned: z.boolean().optional(),
  isStockUpdated: z.boolean().optional(),
  companyId: z.number().optional(),
  companyName: z.string().optional(),
  currencyId: z.number().optional(),
  currencyName: z.string().optional(),
  taxCategoryId: z.number().optional(),
  taxCategoryName: z.string().optional(),
  purchaseTaxTemplateId: z.number().optional(),
  purchaseTaxTemplateName: z.string().optional(),
  supplierAddress: z.string().optional(),
  supplierContact: z.string().optional(),
  supplierAddressDetails: z.string().optional(),
  supplierContactName: z.string().optional(),
  supplierContactEmail: z.string().optional(),
  shippingAddress: z.string().optional(),
  shippingAddressDetails: z.string().optional(),
  companyTRN: z.string().optional(),
  companyBillingAddress: z.string().optional(),
  companyAddressDetails: z.string().optional(),
  creditToId: z.number().optional(),
  creditToName: z.string().optional(),
  isOpeningEntry: z.boolean().optional(),
  totalQuantity: z.number().optional(),
  billAmount: z.number().optional(),
  totalTaxes: z.number().optional(),
  grandTotal: z.number().optional(),
  netTotalAmount: z.number().optional(),
  totalAdvance: z.number().optional(),
  outstandingAmount: z.number().optional(),
  addDiscountApplyOn: z.string().optional(),
  addDiscountPercent: z.number().optional(),
  addDiscountAmount: z.number().optional(),
  writeOffAccountId: z.number().optional(),
  writeOffCostCenterId: z.number().optional(),
  writeOffAmount: z.number().optional(),
  updateInvoiceItemDtos: z.array(z.any()).optional(),
  invoiceVatTaxDetails: z.array(z.any()).optional(),
  invoiceAdvancePayments: z.array(z.any()).optional(),
})

export type CreateInvoiceInput = z.infer<typeof CreateInvoiceSchema>

export type UpdateInvoiceInput = z.infer<typeof UpdateInvoiceSchema>
