import { Position } from "@xyflow/react";
import { AppNode } from ".";

export const ComplianceDocInitialNodes: AppNode[] = [
    {
        id: "compliance_reporting",
        type: "input",
        position: { x: 0, y: 300 },
        data: { label: "Compliance & Reporting" },
        sourcePosition: Position.Right,
    },
    {
        id: "financial_reports",
        position: { x: 300, y: 150 },
        data: { label: "Financial Reports" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "budget_reports",
        position: { x: 300, y: 300 },
        data: { label: "Budget Reports" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "asset_reports",
        position: { x: 300, y: 450 },
        data: { label: "Asset Reports" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "general_ledger",
        position: { x: 600, y: 50 },
        data: { label: "General Ledger Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "trial_balance",
        position: { x: 600, y: 150 },
        data: { label: "Trial Balance Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "profit_loss",
        position: { x: 600, y: 250 },
        data: { label: "Profit and Loss Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "balance_sheet",
        position: { x: 600, y: 350 },
        data: { label: "Balance Sheet" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "budget_summary",
        position: { x: 900, y: 150 },
        data: { label: "Budget Summary Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "budget_variance",
        position: { x: 900, y: 250 },
        data: { label: "Budget Variance Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "fixed_asset_register",
        position: { x: 600, y: 450 },
        data: { label: "Fixed Asset Register" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "asset_depreciation",
        position: { x: 600, y: 550 },
        data: { label: "Asset Depreciation Ledger" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "banking_reports",
        position: { x: 300, y: 600 },
        data: { label: "Banking Reports" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "bank_summary",
        position: { x: 600, y: 650 },
        data: { label: "Bank Account Summary" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "payment_reports",
        position: { x: 300, y: 750 },
        data: { label: "Payment Reports" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
    {
        id: "payment_summary",
        position: { x: 600, y: 750 },
        data: { label: "Payment Summary Report" },
        targetPosition: Position.Left,
        sourcePosition: Position.Right,
    },
]; 