import { WorkingHour } from "@/types/hrms/employee/working-schedule.types"

export const DEFAULT_WORKING_HOURS: WorkingHour[] = [
  {
    name: "Monday Morning",
    dayOfWeek: { label: "Monday", value: "Monday" },
    dayPeriod: { label: "Morning", value: "Morning" },
    workFrom: "08:00",
    workTo: "12:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Monday Lunch Break",
    dayOfWeek: { label: "Monday", value: "Monday" },
    dayPeriod: { label: "Break", value: "Break" },
    workFrom: "12:00",
    workTo: "13:00",
    duration: 1,
    workEntry: 0,
  },
  {
    name: "Monday Afternoon",
    dayOfWeek: { label: "Monday", value: "Monday" },
    dayPeriod: { label: "Afternoon", value: "Afternoon" },
    workFrom: "13:00",
    workTo: "17:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Tuesday Morning",
    dayOfWeek: { label: "Tuesday", value: "Tuesday" },
    dayPeriod: { label: "Morning", value: "Morning" },
    workFrom: "08:00",
    workTo: "12:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Tuesday Lunch Break",
    dayOfWeek: { label: "Tuesday", value: "Tuesday" },
    dayPeriod: { label: "Break", value: "Break" },
    workFrom: "12:00",
    workTo: "13:00",
    duration: 1,
    workEntry: 0,
  },
  {
    name: "Tuesday Afternoon",
    dayOfWeek: { label: "Tuesday", value: "Tuesday" },
    dayPeriod: { label: "Afternoon", value: "Afternoon" },
    workFrom: "13:00",
    workTo: "17:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Wednesday Morning",
    dayOfWeek: { label: "Wednesday", value: "Wednesday" },
    dayPeriod: { label: "Morning", value: "Morning" },
    workFrom: "08:00",
    workTo: "12:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Wednesday Lunch Break",
    dayOfWeek: { label: "Wednesday", value: "Wednesday" },
    dayPeriod: { label: "Break", value: "Break" },
    workFrom: "12:00",
    workTo: "13:00",
    duration: 1,
    workEntry: 0,
  },
  {
    name: "Wednesday Afternoon",
    dayOfWeek: { label: "Wednesday", value: "Wednesday" },
    dayPeriod: { label: "Afternoon", value: "Afternoon" },
    workFrom: "13:00",
    workTo: "17:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Thursday Morning",
    dayOfWeek: { label: "Thursday", value: "Thursday" },
    dayPeriod: { label: "Morning", value: "Morning" },
    workFrom: "08:00",
    workTo: "12:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Thursday Lunch Break",
    dayOfWeek: { label: "Thursday", value: "Thursday" },
    dayPeriod: { label: "Break", value: "Break" },
    workFrom: "12:00",
    workTo: "13:00",
    duration: 1,
    workEntry: 0,
  },
  {
    name: "Thursday Afternoon",
    dayOfWeek: { label: "Thursday", value: "Thursday" },
    dayPeriod: { label: "Afternoon", value: "Afternoon" },
    workFrom: "13:00",
    workTo: "17:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Friday Morning",
    dayOfWeek: { label: "Friday", value: "Friday" },
    dayPeriod: { label: "Morning", value: "Morning" },
    workFrom: "08:00",
    workTo: "12:00",
    duration: 4,
    workEntry: 0.5,
  },
  {
    name: "Friday Lunch Break",
    dayOfWeek: { label: "Friday", value: "Friday" },
    dayPeriod: { label: "Break", value: "Break" },
    workFrom: "12:00",
    workTo: "13:00",
    duration: 1,
    workEntry: 0,
  },
  {
    name: "Friday Afternoon",
    dayOfWeek: { label: "Friday", value: "Friday" },
    dayPeriod: { label: "Afternoon", value: "Afternoon" },
    workFrom: "13:00",
    workTo: "17:00",
    duration: 4,
    workEntry: 0.5,
  },
]
