export const HRMSApiEndpoints = {
  fetchAllEmployees: "/employee/get-all-employee?sort=desc",
  fetchEmployeeById: (id: number) => `/employee/${id}`,
  deleteEmployee: (id: number) => `/employee/delete-employee/${id}`,
  deleteEmployees: "/employee/delete-employees",
  createEmployee: "/employee/add-employee",
  updateEmployee: "/employee/update-employee",
  fetchAllDepartments: "/department/get-all-department?sort=desc",
  fetchDepartmentStatistics: "/dashboard/get-department-employee-statistics",
  deleteDepartment: (id: number) => `/department/delete-department/${id}`,
  deleteDepartments: "/department/delete-departments",

  fetchAllJobPositions: "/jobposition/get-all-job-position?sort=desc",
  fetchJobPositionById: (id: number) => `/jobposition/${id}`,
  createJobPosition: "/jobposition/add-job-position",
  updateJobPosition: "/jobposition/update-job-position",
  deleteJobPosition: (id: number) => `/jobposition/delete-job-position/${id}`,
  deleteJobPositions: "/jobposition/delete-job-positions",

  createDepartment: "/department/add-department",
  updateDepartment: "/department/update-department",
  fetchAllEmployeeTypes: "/employeetype/get-all-employee-type?sort=desc",
  deleteEmployeeType: (id: number) =>
    `/employeetype/delete-employee-type/${id}`,
  deleteEmployeeTypes: "/employeetype/delete-employee-types",
  createEmployeeType: "/employeetype/add-employee-type",
  updateEmployeeType: "/employeetype/update-employee-type",
  fetchAllEmploymentTypes: "/employmenttype/get-all-employment-type?sort=desc",
  deleteEmploymentType: (id: number) =>
    `/employmenttype/delete-employment-type/${id}`,
  deleteEmploymentTypes: "/employmenttype/delete-employment-types",
  createEmploymentType: "/employmenttype/add-employment-type",
  updateEmploymentType: "/employmenttype/update-employment-type",
  fetchAllResumeTypes: "/resumetype/get-all-resumetype?sort=desc",
  fetchResumeTypeById: (id: number) => `/resumetype/${id}`,
  fetchResumeById: (id: number) => `/resume/${id}`,
  createResume: "/resume/add-resume",
  updateResume: "/resume/update-resume",
  deleteResume: (id: number) => `/resume/delete-resume/${id}`,
  deleteResumeType: (id: number) => `/resumetype/delete-resumetype/${id}`,
  deleteResumeTypes: "/resumetype/delete-resumeTypes",
  createResumeType: "/resumetype/add-resumetype",
  updateResumeType: "/resumetype/update-resumetype",
  fetchWorkInfoById: (id: number) => `/workinformation/${id}`,
  createWorkInfo: `/workinformation/add-workInformation`,
  updateWorkInfo: `/workinformation/update-workInformation`,
  deleteWorkInformation: (id: number) =>
    `/workinformation/delete-workInformation/${id}`,
  fetchPrivateInfoById: (id: number) => `/privateinformation/${id}`,
  createPrivateInformation: `/privateinformation/add-private-information`,
  updatePrivateInformation: `/privateinformation/update-private-information`,
  deletePrivateInformation: (id: number) =>
    `/privateinformation/delete-private-information/${id}`,
  fetchAllWorkAddresses: "/workingaddress/get-all-working-address?sort=desc",
  fetchWorkAddressById: (id: number) => `/workingaddress/${id}`,
  deleteWorkAddress: (id: number) =>
    `/workingaddress/delete-working-address/${id}`,
  deleteWorkAddresses: "/workingaddress/delete-working-addresses",
  createWorkAddress: "/workingaddress/add-working-address",
  updateWorkAddress: "/workingaddress/update-working-address",
  fetchAllWorkingSchedules:
    "/workingschedule/get-all-working-schedule?sort=desc",
  fetchWorkingScheduleById: (id: number) => `/workingschedule/${id}`,
  deleteWorkingSchedule: (id: number) =>
    `/workingschedule/delete-working-schedule/${id}`,
  deleteWorkingSchedules: "/workingschedule/delete-working-schedules",
  createWorkingSchedule: "/workingschedule/add-working-schedule",
  updateWorkingSchedule: "/workingschedule/update-working-schedule",
  fetchAllAttendances: "/attendance/get-all-attendance?sort=desc",
  fetchAttendanceById: (id: number) => `/attendance/attendance-list/${id}`,
  deleteAttendance: (id: number) => `/attendance/delete-attendance/${id}`,
  deleteAttendances: "/attendance/bulk-delete",
  createAttendance: "/attendance/add-attendance",
  attendanceCheckIn: "/attendance/checkin",
  attendanceCheckOut: "/attendance/checkout",
  updateAttendance: "/attendance/update-attendance",
  fetchAllReconciliations: "/reconciliationrequest/get-all-request?sort=desc",
  fetchReconciliationById: (id: number) => `/reconciliationrequest/${id}`,
  createReconciliation: "/reconciliationrequest/add-request",
  reviewReconciliation: "/reconciliationrequest/review-request",
  deleteReconciliation: (id: number) =>
    `/reconciliationrequest/delete-request/${id}`,
  deleteReconciliations: "/reconciliationrequest/bulk-delete",
  fetchAllLeaveTypes: "/leavetype/get-all-leave-type?sort=desc",
  createLeaveType: "/leavetype/add-leave-type",
  updateLeaveType: "/leavetype/update-leave-type",
  deleteLeaveType: (id: number) => `/leavetype/delete-leave-type/${id}`,
  deleteLeaveTypes: "/leavetype/delete-leave-types",
  fetchEmployeeAttendanceStatistics: (employeeId: number) =>
    `/attendance/get-employee-attendance-statistics/${employeeId}`,
  fetchEmployeeAttendance: (employeeId: number) =>
    `/attendance/get-employee-attendance/${employeeId}`,
  fetchAllOffDays: "/offday/get-all-offday?sort=desc",
  fetchOffDayById: (id: number) => `/offday/${id}`,
  deleteOffDay: (id: number) => `/offday/delete-offday/${id}`,
  deleteOffDays: "/offday/bulk-delete",
  createOffDay: "/offday/add-offday",
  updateOffDay: "/offday/update-offday",
  fetchAllLeaveAllocations:
    "/leaveallocation/get-all-leaveallocation?sort=desc",
  createLeaveAllocation: "/leaveallocation/add-allocation",
  updateLeaveAllocation: "/leaveallocation/update-allocation",
  deleteLeaveAllocation: (id: number) =>
    `/leaveallocation/delete-allocation/${id}`,
  deleteLeaveAllocations: "/leaveallocation/delete-allocations",
  fetchAllLeaveRequest: "/timeoff/get-all-timeOff?sort=desc",
  createLeaveRequest: "/timeoff/add-timeOff",
  updateLeaveRequest: "/timeoff/update-timeOff-status",
  deleteLeaveRequest: (id: number) => `/timeoff/delete-timeOff/${id}`,
  fetchCompliance: "/nitaqat/get-compliance",
  sendEmail: "/nitaqat/send-email",
  fetchAllRecruitments: "/jobPosting/get-all-job-posting?sort=desc",
  fetchRecruitmentById: (id: number) => `/jobPosting/${id}`,
  createRecruitment: "/jobPosting/add-job-posting",
  updateRecruitment: "/jobPosting/update-job-posting",
  deleteRecruitment: (id: number) => `/jobPosting/delete-job-posting/${id}`,
  deleteRecruitments: "/jobPosting/delete-job-postings",
  fetchAllApplications: "/jobapplication/get-all-job-application?sort=desc",
  fetchApplicationById: (id: number) => `/jobapplication/${id}`,
  createApplication: "/jobapplication/add-job-application",
  updateApplication: "/jobapplication/update-job-application",
  updateApplicationStatus: "/jobapplication/update-job-application-status",
  deleteApplication: (id: number) =>
    `/jobapplication/delete-job-application/${id}`,
  deleteApplications: "/jobapplication/bulk-delete",
  fetchAllSalaryCategories: "/salarycategory/get-all-salaryCategory?sort=desc",
  createSalaryCategory: "/salarycategory/add-salary-category",
  updateSalaryCategory: "/salarycategory/update-salary-category",
  deleteSalaryCategory: (id: number) =>
    `/salarycategory/delete-salary-category/${id}`,
  deleteSalaryCategories: "/salarycategory/delete-salary-categories",
  fetchSalaryCategory: (id: number) => `/salarycategory/${id}`,
  fetchAllSalaryRules: "/salaryrule/get-all-salary-rules?sort=desc",
  createSalaryRule: "/salaryrule/add-salary-rule",
  updateSalaryRule: "/salaryrule/update-salary-rule",
  deleteSalaryRule: (id: number) => `/salaryrule/delete-salary-rule/${id}`,
  deleteSalaryRules: "/salaryrule/delete-salary-rules",
  fetchSalaryRuleById: (id: number) => `/salaryrule/${id}`,
  fetchAllSalaryStructureTypes:
    "/salarystructuretype/get-all-salary-structure-type?sort=desc",
  createSalaryStructureType: "/salarystructuretype/add-salary-structure-type",
  updateSalaryStructureType:
    "/salarystructuretype/update-salary-structure-type",
  deleteSalaryStructureType: (id: number) =>
    `/salarystructuretype/delete-salary-structure-type/${id}`,
  deleteSalaryStructureTypes:
    "/salarystructuretype/delete-salary-structure-types",
  fetchAllSalaryStructures:
    "/salarystructure/get-all-salary-structure?sort=desc",
  createSalaryStructure: "/salarystructure/add-salary-structure",
  updateSalaryStructure: "/salarystructure/update-salary-structure",
  deleteSalaryStructure: (id: number) =>
    `/salarystructure/delete-salary-structure/${id}`,
  deleteSalaryStructures: "/salarystructure/delete-salary-structures",
  fetchSalaryStructureById: (id: number) => `/salarystructure/${id}`,
  fetchAllEmployeeContracts:
    "/employeecontract/get-all-employee-contract?sort=desc",
  createEmployeeContract: "/employeecontract/add-employee-contract",
  updateEmployeeContract: "/employeecontract/update-employee-contract",
  deleteEmployeeContract: (id: number) =>
    `/employeecontract/delete-employee-contract/${id}`,
  deleteEmployeeContracts: "/employeecontract/bulk-delete",
  fetchEmployeeContractById: (id: number) => `/employeecontract/${id}`,
  fetchAllAppraisalTemplates: "/template/get-all-template?sort=desc",
  createAppraisalTemplate: "/template/add-template",
  updateAppraisalTemplate: "/template/update-template",
  deleteAppraisalTemplate: (id: number) => `/template/delete-template/${id}`,
  deleteAppraisalTemplates: "/template/delete-templates",
  fetchAppraisalTemplateById: (id: number) => `/template/${id}`,
  fetchAllAppraisals: "/appraisal/get-all-appraisals?sort=desc",
  createAppraisal: "/appraisal/add-appraisal",
  updateAppraisal: "/appraisal/update-appraisal",
  deleteAppraisal: (id: number) => `/appraisal/delete-appraisal${id}`,
  deleteAppraisals: "/appraisal/delete-appraisals",
  fetchAppraisalById: (id: number) => `/appraisal/${id}`,
  fetchAllPayslips: "/payslip/get-all-payslip?sort=desc",
  createPayslip: "/payslip/add-payslip",
  updatePayslip: "/payslip/update-payslip",
  deletePayslip: (id: number) => `/payslip/delete-payslip/${id}`,
  updatePayslipStatus: "/payslip/update-payslip-status",
  deletePayslips: "/payslip/delete-payslips",
  fetchPayslipById: (id: number) => `/payslip/${id}`,
  fetchEmployeeContractByEmployeeId: (id: number) => `/employeecontract/${id}`,
  fetchAllGoals: "/goal/get-all-goal?sort=desc",
  createGoal: "/goal/add-goal",
  updateGoal: "/goal/update-goal",
  deleteGoal: (id: number) => `/goal/delete-goal/${id}`,
  deleteGoals: "/goal/delete-goals",
  fetchGoalById: (id: number) => `/goal/${id}`,
  fetchAllFolders: "/folder/get-all-folder",
  createFolder: "/folder/add-folder",
  updateFolder: "/folder/update-folder",
  deleteFolder: (id: number) => `/folder/delete-folder/${id}`,
  deleteFolders: "/folder/delete-folders",
  fetchFolderById: (id: number) => `/folder/${id}`,
  createFile: "/uploadedfile/add-uploaded-file",
  deleteFile: (id: number) => `/uploadedfile/delete-uploaded-file/${id}`,
  deleteFiles: "/uploadedfile/delete-uploaded-files",
  fetchAllFiles: "/uploadedfile/get-all-uploaded-file?sort=desc",
  fetchFileById: (id: number) => `/uploadedfile/${id}`,
  fetchAllTrainingPrograms:
    "/trainingprogram/get-all-training-program?sort=desc",
  createTrainingProgram: "/trainingprogram/add-training-program",
  updateTrainingProgram: "/trainingprogram/update-training-program",
  deleteTrainingProgram: (id: number) =>
    `/trainingprogram/delete-training-program/${id}`,
  deleteTrainingPrograms: "/trainingprogram/delete-trainingprograms",
  fetchTrainingProgramById: (id: number) => `/trainingprogram/${id}`,
  fetchAllTrainingSessions: "/session/get-all-session?sort=desc",
  fetchTrainingSessionById: (id: number) => `/session/${id}`,
  createTrainingSession: "/session/add-session",
  updateTrainingSession: "/session/update-session",
  deleteTrainingSession: (id: number) => `/session/${id}`,
  deleteTrainingSessions: "/session/delete-sessions",

  // Participants
  fetchAllParticipants: "/participants/get-all-participants",
  fetchParticipantById: (id: number) => `/participant/get-participant/${id}`,
  fetchParticipantsByProgram: (programId: number) =>
    `/participants/get-participants-by-program/${programId}`,
  createParticipant: "/participant/add-participants",
  updateParticipant: "/participant/update-participants",
  updateParticipantAttendance: (id: number) => `/participant/${id}/attendance`,
  updateParticipantFeedback: (id: number) => `/participant/${id}/feedback`,
  deleteParticipant: (id: number) => `/participant/${id}`,
  deleteParticipants: "/participant/delete-participants",
  fetchAllTrainingAttendances:
    "/trainingattendance/get-all-training-attendance?sort=desc",
  createTrainingAttendance: "/trainingattendance/add-training-attendance",
  updateTrainingAttendance: "/trainingattendance/update-training-attendance",
  deleteTrainingAttendance: (id: number) =>
    `/trainingattendance/delete-training-attendance/${id}`,
  deleteTrainingAttendances: "/trainingattendance/delete-training-attendances",
  fetchTrainingAttendanceById: (id: number) => `/trainingattendance/${id}`,

  // Training Feedback endpoints
  fetchAllTrainingFeedbacks:
    "/trainingfeedback/get-all-training-feedback?sort=desc",
  fetchTrainingFeedbackById: (id: number) => `/trainingfeedback/${id}`,
  createTrainingFeedback: "/trainingfeedback/add-training-feedbacks",
  updateTrainingFeedback: "/trainingfeedback/update-training-feedbacks",
  deleteTrainingFeedback: (id: number) =>
    `/trainingfeedback/delete-training-feedback/${id}`,
  deleteTrainingFeedbacks: "/trainingfeedback/delete-training-feedbacks",
  fetchEmployeeMonthlyReport: "/report/employee-monthly-report",
  fetchEmployeeDailyAttendanceReport:
    "/report/employee-daily-attendance-report",
  fetchEmployeeTimeOffReport: "/report/employee-daily-timeoff-report",
  fetchEmployeeYearlyOffdayReport: "/report/employee-year-wise-offday-report",
  fetchSaudiEmployeeMonthlyReport: "/report/saudi-employee-monthly-report",
  fetchExpatriateEmployeeMonthlyReport:
    "/report/expatriate-employee-monthly-report",
}
