export const crmRoutes = {
  dashboard: "/crm/dashboard",
  organization: "/crm/dashboard/org",
  leadAnalytics: "/crm/dashboard/analytics",
  insights: "/crm/dashboard/insights",
  users: "/users",
  profile: "/crm/users/profile",
  viewProfile: (id: string) => `/users/${id}`,
  editProfile: (id: string) => `/users/${id}/edit`,
  editProduct: (id: string) => `/crm/items/${id}/edit`,
  editLead: (id: string) => `/crm/leads/${id}/edit`,
  editOpportunity: (id: string) => `/crm/opportunities/${id}/edit`,
  viewOpportunity: (id: string) => `/crm/opportunities/${id}`,
  viewSalesOrder: (id: string) => `/crm/sales-orders/${id}`,
  paySalesOrder: (id: string) => `/crm/sales-orders/${id}/payment`,
  editSalesOrder: (id: string) => `/crm/sales-orders/${id}/edit`,
  editInvoice: (id: string) => `/crm/sales-invoice/${id}/edit`,
  editSalesInvoice: (id: string) => `/crm/sales-invoice/${id}/payment`,
  viewInvoice: (id: string) => `/crm/sales-invoice/${id}`,
  payInvoice: (id: string) => `/crm/sales-invoice/${id}/payment`,
  paymentRequest: (id: string) => `/crm/sales-invoice/${id}/payment-request`,
  viewCustomer: (id: string) => `/crm/customers/${id}`,
  editCustomer: (id: string) => `/crm/customers/${id}/edit`,
  customers: "/crm/customers",
  createCustomer: "/crm/customers/create",
  resetPassword: "/crm/users/reset-password",
  roles: "/users/roles",
  activityLog: "/users/logs",
  userCreate: "/users/create",
  roleCreate: "/users/roles/create",
  permissions: "/users/permissions",
  permissionCreate: "/users/permissions/create",
  stockCreate: "/crm/stocks/create",
  items: "/crm/items",
  createProduct: "/crm/items/create",
  createMeeting: "/crm/meetings/create",
  campaignCreate: "/crm/campaigns/create",
  leadCreate: "/crm/leads/create",
  categoryCreate: "/crm/categories/create",
  attributeCreate: "/crm/attributes/create",
  opportunityCreate: "/crm/opportunities/create",
  quotationCreate: "/crm/quotation/create",
  salesOrdersCreate: "/crm/salesorders/create",
  invoiceCreate: "/crm/sales-invoice/create",
  orderCreate: "/crm/orders/create",
  categories: "/crm/categories",
  attributes: "/crm/attributes",
  stocks: "/crm/stocks",
  quotation: "/crm/quotation",
  salesorders: "/crm/salesorders",
  contacts: "/crm/contacts",
  contactDetails: (id: string) => `/crm/contacts/${id}`,
  createContact: "/crm/contacts/create",
  editContact: (id: string) => `/crm/contacts/${id}/edit`,
  leads: "/crm/leads",
  opportunities: "/crm/opportunities",
  deals: "/crm/deals",
  tasks: "/crm/tasks",
  statusBoard: "/crm/tasks/status-board",
  activities: "/crm/activities",
  campaigns: "/crm/campaigns",
  campaignDetails: (id: string) => `/crm/campaigns/${id}`,
  leadDetails: (id: string) => `/crm/leads/${id}`,
  createCampaign: "/crm/campaigns/create",
  editCampaign: (id: string) => `/crm/campaigns/${id}/edit`,
  createTask: "/crm/tasks/create",
  editTask: (id: string) => `/crm/tasks/${id}/edit`,
  createActivity: "/crm/activities/create",
  editActivity: (id: string) => `/crm/activities/${id}/edit`,
  bills: "/crm/billings",
  createBill: "/crm/billings/create",
  billDetails: (id: string) => `/crm/billings/${id}`,
  editBill: (id: string) => `/crm/billings/${id}/edit`,
  payBill: (id: string) => `/crm/billings/${id}/payment`,
  viewQuotation: (id: string) => `/crm/quotation/${id}`,
  editQuotation: (id: string) => `/crm/quotation/${id}/edit`,
  editTarget: (id: string) => `/crm/targets/${id}/edit`,
  purchaseOrders: "/crm/purchase-orders",
  invoices: "/crm/sales-invoice",
  createInvoice: "/crm/sales-invoice/create",
  targets: "/crm/targets",
  createTarget: "/crm/targets/create",
  createPurchaseOrders: "/crm/purchase-orders/create",
  salesOrders: "/crm/sales-orders",
  salesInvoice: "/crm/sales-invoice",
  meetings: "/crm/meetings",
  eventCalendar: "/crm/meetings/event-calendar",
  tickets: "/crm/tickets",
  slas: "/crm/slas",
  messages: "/crm/messages",
  documentation: "/crm/documentation",
  notifications: "/crm/notifications",
  editMeeting: (id: string) => `/crm/meetings/${id}/edit`,
  editTicket: (id: string) => `/crm/tickets/${id}/edit`,
  createTicket: "/crm/tickets/create",
  createSalesOrders: "/crm/sales-orders/create",
  reminders: "/crm/reminders",
  settings: "/crm/settings",
  emailSettings: "/crm/settings/email",
  approval: "/crm/approval",
  approvals: "/crm/approvals",
  salesReport: "/crm/reports/sales",
  leadsByCompany: "/crm/reports/leads-by-company",
  leadsByStatus: "/crm/reports/leads-by-status",
  campaignsReport: "/crm/reports/campaigns",
  opportunityReport: "/crm/reports/opportunity",
  ticketsReport: "/crm/reports/tickets",
}
